name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t endpoint:latest .
    
    - name: Run Docker image
      run: docker run -d -p 3000:80 endpoint:latest # -d runs image as background process

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: run tests
      uses: SloaneTribble/github-actions/apprentice-action@master
