name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-run-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t endpoint:latest .


  # test:
  #   runs-on:
  #     ubuntu-latest
  #   steps:
  #     - name: run tests
  #       uses: liatrio/github-actions/apprentice-action@master
