name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t stribble/apprenticeship-interview:${{ github.sha }} .
    
    - name: Run Docker container from image
      run: |
        docker run -d -p 80:80 stribble/apprenticeship-interview:${{ github.sha }}

    - name: Run tests
      uses: liatrio/github-actions/apprentice-action@921d5abcef26851810ca11a97e1418c1c3f95e0b

    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker push
      run: docker push stribble/apprenticeship-interview:${{ github.sha }}
        
        
    
