name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t endpoint:latest .
    
    - name: Run Docker image with debug log
      run: |
        container_id=$(docker run -d -p 80:80 endpoint:latest) 

        # Display network details
        echo "::group::Docker Network Inspection"
        docker network inspect bridge
        echo "::endgroup::"

        # Display running containers
        echo "::group::Running Containers"
        docker ps
        echo "::endgroup::"
    
        # Extract the port mapping from the container's metadata
        port_mapping=$(docker port $container_id)
    
        # Display the port information in the logs
        echo "Container is running on port $port_mapping"

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@921d5abcef26851810ca11a97e1418c1c3f95e0b

      
        
    
